In [ ]:
import numpy as np
empty_array = np.zeros((2,2))
#Print the 2 dimensional empty array
print(empty_array)

[[0. 0.]
 [0. 0.]]


Q2 Initialize an all one array with size 4X2.**bold text**

In [ ]:
import numpy as np
array = np.ones((4, 2))
#Print the array with 4 * 2 size
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Q3 Return a new array of given shape and type, filled with fill value.

In [ ]:
import numpy as np

shape = (4,4)
filled_value = 1
filled_array = np.full(shape, filled_value)
print(f"filled array : {filled_array}")

filled array : [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Q4 Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np
given_array = np.array([[1, 1], [1, 1]])
zero_array = np.zeros_like( given_array)
#Printing the given array.
print(zero_array)



[[0 0]
 [0 0]]


Q5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np
given_array = np.array([[1,2,3], [2,3,4], [1,5,6]]) #Random given array.
new_array = np.ones_like(given_array)
print(new_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Q 6 For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
import numpy as np

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)

print(numpy_array)



[1 2 3 4]


4.1.1

Q1 Create an array with values ranging from 10 to 49. {Hint:np.arrange()}

In [2]:
import numpy as np

array = np.arange(10, 50)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Q2  Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()

In [3]:
import numpy as np

# Create an array with values ranging from 0 to 8
array = np.arange(9)

# Reshape the array into a 3x3 matrix
matrix = array.reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Q3  Create a 3X3 identity matrix.{Hint:np.eye()}

In [4]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q4 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}

In [5]:
import numpy as np

# Create a random array of size 30
random_array = np.random.random(30)

# Find the mean of the array
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Mean of the Array:", mean_value)


Random Array: [0.47698275 0.64706761 0.54200599 0.16265298 0.66949597 0.54092069
 0.14949113 0.52827478 0.30949438 0.30320863 0.27512218 0.53680567
 0.12058999 0.58771492 0.26502595 0.29530908 0.50137805 0.89291258
 0.23772878 0.29003738 0.2722598  0.76240928 0.692153   0.18439607
 0.81797264 0.22578072 0.03466319 0.8300546  0.00947654 0.8329905 ]
Mean of the Array: 0.43314586009191


Q 5 5. Create a 10X10 array with random values and find the minimum and maximum values.

In [6]:
import numpy as np

# Create a 10x10 array with random values
random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print("Random Array:\n", random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
 [[0.72271642 0.33749108 0.54550259 0.10545534 0.27724897 0.53519752
  0.07382187 0.03400669 0.21259624 0.53467945]
 [0.60906514 0.7333838  0.33493748 0.96144692 0.1497742  0.16823789
  0.60453776 0.20504317 0.08666217 0.22298187]
 [0.11947028 0.87122421 0.14063485 0.0645496  0.05723105 0.85566352
  0.16228174 0.26742065 0.95742011 0.2203943 ]
 [0.54840589 0.83300502 0.26800627 0.36929407 0.28922424 0.38893482
  0.31311438 0.63853066 0.25300558 0.44843935]
 [0.60324078 0.29849233 0.55500583 0.50783201 0.29225629 0.48559582
  0.06318303 0.93514671 0.49500786 0.21713903]
 [0.63743915 0.42283881 0.44354123 0.24120891 0.30690529 0.25283587
  0.40735309 0.27710804 0.22887377 0.96284258]
 [0.83495113 0.14972398 0.27767255 0.89548673 0.30962162 0.25971471
  0.106999   0.92599621 0.83145262 0.85137049]
 [0.77319067 0.17113647 0.3001573  0.41244499 0.68889888 0.66654626
  0.25263347 0.00499601 0.07696875 0.50679481]
 [0.59074796 0.93104054 0.26031318 0.29357746 0.37029861 0.534402

 6. Create a zero array of size 10 and replace 5th element with 1.

In [7]:
import numpy as np

# Create a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
zero_array[4] = 1

print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


 Q 7 Reverse an array arr = [1,2,0,0,4,0].

In [8]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]

print(reversed_arr)


[0 4 0 0 2 1]


Q 8 Create a 2d array with 1 on border and 0 inside.

In [9]:
import numpy as np

# Create a 2D array of zeros with the desired shape
array = np.zeros((5, 5))

# Set the border elements to 1
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1

print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Q 9 Create a 8X8 matrix and fill it with a checkerboard pattern.

In [10]:
import numpy as np

# Create an 8x8 matrix
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the matrix with a checkerboard pattern
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q 1  For the following arrays:
 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12]);
 Complete all the task using numpy:
 1. Add the two array.
 2. Subtract the two array.
 3. Multiply the array with any integers of your choice.
 4. Find the square of each element of the array.
 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.
 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [11]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
addition = np.add(x, y)
print("Addition:\n", addition)

# 2. Subtract the two arrays
subtraction = np.subtract(x, y)
print("Subtraction:\n", subtraction)

#Multiply the array with any integer (let's choose 2)
multiplication = x * 2
print("Multiplication:\n", multiplication)

#Find the square of each element of the array
square = np.square(x)
print("Square:\n", square)

#Find the dot product between: v and w; x and v; x and y
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("Dot product v and w:", dot_vw)
print("Dot product x and v:\n", dot_xv)
print("Dot product x and y:\n", dot_xy)

#Concatenate x and y along rows and concatenate v and w along columns
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))

print("Concatenate x and y along rows:\n", concat_xy_row)
print("Concatenate v and w along columns:\n", concat_vw_col)

#Concatenate x and v; if you get an error, observe and explain why
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenate x and v:\n", concat_xv)
except ValueError as e:
    print("Error:", e)


Addition:
 [[ 6  8]
 [10 13]]
Subtraction:
 [[-4 -4]
 [-4 -3]]
Multiplication:
 [[ 2  4]
 [ 6 10]]
Square:
 [[ 1  4]
 [ 9 25]]
Dot product v and w: 219
Dot product x and v:
 [29 77]
Dot product x and y:
 [[19 22]
 [50 58]]
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [12]:
# problem 4
import numpy as np

A = np.array([[3, 4], [7, 8]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by its inverse
I = np.dot(A, A_inv)

print("A:\n", A)
print("A_inv:\n", A_inv)
print("A * A_inv:\n", I)



A:
 [[3 4]
 [7 8]]
A_inv:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [13]:
B = np.array([[5, 3], [2, 1]])

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n", AB)
print("BA:\n", BA)


AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [14]:
# Compute the transpose of AB
AB_T = np.transpose(AB)

# Compute the product of the transposes of B and A
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("(AB)^T:\n", AB_T)
print("B^T A^T:\n", BT_AT)


(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]


In [15]:
# Define the matrices A and B
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

print("Solution X:\n", X)


Solution X:
 [ 2.  1. -2.]


In [16]:
#4.2
#Q1
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

# Measure the time taken for element-wise addition
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(1000000)]
end_time = time.time()

print("Time taken for element-wise addition using Python lists:", end_time - start_time)


Time taken for element-wise addition using Python lists: 0.1566159725189209


In [17]:
#Q2
import numpy as np

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Measure the time taken for element-wise addition
start_time = time.time()
result_array = array1 + array2
end_time = time.time()

print("Time taken for element-wise addition using NumPy arrays:", end_time - start_time)


Time taken for element-wise addition using NumPy arrays: 0.004288434982299805


In [18]:
#Q3
# Measure the time taken for element-wise multiplication
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()

print("Time taken for element-wise multiplication using Python lists:", end_time - start_time)



Time taken for element-wise multiplication using Python lists: 0.1641523838043213


In [19]:
#Q4
# Measure the time taken for element-wise multiplication
start_time = time.time()
result_array = array1 * array2
end_time = time.time()

print("Time taken for element-wise multiplication using NumPy arrays:", end_time - start_time)


Time taken for element-wise multiplication using NumPy arrays: 0.00893402099609375


In [20]:
#5
# Measure the time taken for dot product
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))
end_time = time.time()

print("Time taken for dot product using Python lists:", end_time - start_time)


Time taken for dot product using Python lists: 0.15079498291015625


In [21]:
#Q6
# Measure the time taken for dot product
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()

print("Time taken for dot product using NumPy arrays:", end_time - start_time)


Time taken for dot product using NumPy arrays: 0.0032198429107666016


In [22]:
#Q7
# Create two matrices of size 1000x1000
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]

# Measure the time taken for matrix multiplication
start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(matrix1_row, matrix2_col)) for matrix2_col in zip(*matrix2)] for matrix1_row in matrix1]
end_time = time.time()

print("Time taken for matrix multiplication using Python lists:", end_time - start_time)


Time taken for matrix multiplication using Python lists: 198.3295238018036


In [23]:
#q8
# Create two NumPy arrays of size 1000x1000
matrix1 = np.arange(1000000).reshape(1000, 1000)
matrix2 = np.arange(1000000).reshape(1000, 1000)

# Measure the time taken for matrix multiplication
start_time = time.time()
result_matrix = np.dot(matrix1, matrix2)
end_time = time.time()

print("Time taken for matrix multiplication using NumPy arrays:", end_time - start_time)


Time taken for matrix multiplication using NumPy arrays: 1.3156206607818604
